version: '3.8'

services:
  transvoz-app:
    build: .
    container_name: transvoz-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/transvoz
      - SPRING_DATASOURCE_USERNAME=transvoz
      - SPRING_DATASOURCE_PASSWORD=transvoz123
      - APP_STORAGE_S3_ENDPOINT=http://minio:9000
      - APP_STORAGE_S3_ACCESS_KEY=minioadmin
      - APP_STORAGE_S3_SECRET_KEY=minioadmin123
      - APP_STORAGE_TYPE=s3
      - JWT_SECRET=transvoz-super-secret-jwt-key-for-production
      - TRANSCRIPTION_API_KEY=your-transcription-api-key
      - WEBHOOK_URL=http://transvoz-app:8080/api/v1/webhook/transcription
    depends_on:
      - postgres
      - minio
    volumes:
      - app-uploads:/app/uploads
      - app-logs:/app/logs
    networks:
      - transvoz-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: transvoz-postgres
    environment:
      - POSTGRES_DB=transvoz
      - POSTGRES_USER=transvoz
      - POSTGRES_PASSWORD=transvoz123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./scripts/roles.sql:/docker-entrypoint-initdb.d/02-roles.sql
    networks:
      - transvoz-network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: transvoz-minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - transvoz-network
    restart: unless-stopped

volumes:
  postgres-data:
  minio-data:
  app-uploads:
  app-logs:

networks:
  transvoz-network:
    driver: bridge
