version: '3.8'

services:
  postgres-dev:
    image: postgres:15-alpine
    container_name: transvoz-postgres-dev
    environment:
      - POSTGRES_DB=transvoz_dev  
      - POSTGRES_USER=transvoz
      - POSTGRES_PASSWORD=transvoz123
    ports:
      - "5433:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./scripts/roles.sql:/docker-entrypoint-initdb.d/02-roles.sql
      - ./scripts/sample-data.sql:/docker-entrypoint-initdb.d/03-sample-data.sql
    networks:
      - transvoz-dev-network

  minio-dev:
    image: minio/minio:latest
    container_name: transvoz-minio-dev
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-dev-data:/data
    networks:
      - transvoz-dev-network

volumes:
  postgres-dev-data:
  minio-dev-data:

networks:
  transvoz-dev-network:
    driver: bridge
