spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 50
      
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        
app:
  storage:
    type: s3
    s3:
      endpoint: ${S3_ENDPOINT}
      bucket: ${S3_BUCKET}
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
      
  transcription:
    external-api:
      url: ${TRANSCRIPTION_API_URL}
      api-key: ${TRANSCRIPTION_API_KEY}
      webhook-url: ${WEBHOOK_URL}

logging:
  level:
    com.transvoz: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
