spring:
  application:
    name: transvoz
  profiles:
    active: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/transvoz
    username: transvoz
    password: transvoz123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
    
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      
  security:
    require-ssl: false

# Application specific configurations
app:
  jwt:
    secret: ${JWT_SECRET:transvoz-super-secret-key-change-in-production-environment}
    access-token-expiration: 3600000 # 1 hour
    refresh-token-expiration: 2592000000 # 30 days
    
  storage:
    type: local # local or s3
    local:
      upload-dir: ./uploads
    s3:
      endpoint: ${S3_ENDPOINT:http://localhost:9000}
      bucket: ${S3_BUCKET:transvoz-audio}
      access-key: ${S3_ACCESS_KEY:minioadmin}
      secret-key: ${S3_SECRET_KEY:minioadmin}
      region: ${S3_REGION:us-east-1}
      
  transcription:
    external-api:
      url: ${TRANSCRIPTION_API_URL:https://api.example.com}
      api-key: ${TRANSCRIPTION_API_KEY:your-api-key-here}
      webhook-url: ${WEBHOOK_URL:http://localhost:8080/api/v1/webhook/transcription}
      timeout: 30000
      
  audio:
    max-duration-hours: 4
    max-file-size-mb: 200
    allowed-formats: mp3,wav,m4a,flac,aac,ogg
    
  crypto:
    algorithm: AES-256-GCM
    key: ${CRYPTO_KEY:transvoz-encryption-key-32-bytes!!}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# Logging
logging:
  level:
    com.transvoz: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  info:
    title: TransVoz API
    description: Audio transcription service with speaker diarization
    version: 1.0.0
